// src/components/home/About.tsx
import { useEffect, useState } from 'preact/hooks';
import './About.scss';

const positiveMessages = [
  'he believes in you.',
  "he thinks you're awesome.",
  'he thinks you belong here.',
  'he knows you belong here.',
  "he thinks you've got this.",
  'he knows you can.',
]
const images = [5, 6, 7, 8, 10]

function About() {
	
  const [michaelImage, setMichaelImage] = useState('');
  const [positiveMessage, setPositiveMessage] = useState('');

	const recycle = () => {
		const randomMessage = Math.floor(Math.random() * positiveMessages.length);
		const randomImage = Math.floor(Math.random() * images.length);
		setPositiveMessage(positiveMessages[randomMessage]);
		setMichaelImage(`https://res.cloudinary.com/dk3rdh3yo/image/upload/g_auto,f_auto/v1607302424/ograph_${images[randomImage]}.png`);
	}

	recycle();

	return (
	  <section class="about stripe">
    <div class="aboutBody">
      <img src={michaelImage} alt="Michael making faces" onClick={recycle} />
      <div>
        <h2>About <span>Michael</span></h2>
        <p>
          At work, he leads the Developer Relations team at
          <a href="https://deepgram.com">Deepgram</a> where he gets to play with
          awesome APIs. You can also catch him giving talks at various events,
          sharing videos on
          <a href="https://youtube.com/baldbeardedbuilder">YouTube</a>, or
          streaming on
          <a href="https://twitch.tv/baldbeardedbuilder">Twitch</a>.
        </p>
        <p>
          But more importantly,<span>{positiveMessage}</span>
        </p>
      </div>
    </div>
  </section>
	);
}

export default About;

// site/components/About.vue
<template>
  <section class="stripe">
    <div class="about">
      <img :src="michaelImage" alt="Picture of Michael" @click="recycle()" />
      <div>
        <h2>
          About
          <span>Michael</span>
        </h2>
        <p>
          At work, he leads the Developer Relations team at
          <a href="https://deepgram.com">Deepgram</a> where he gets to play with
          awesome APIs. You can also catch him giving talks at various events,
          sharing videos on
          <a
            href="https://youtube.com/baldbeardedbuilder"
          >YouTube</a>, or
          streaming on
          <a href="https://twitch.tv/baldbeardedbuilder">Twitch</a>.
        </p>
        <p>
          But more importantly,
          <span>{{ positiveMessage }}</span>
        </p>
      </div>
    </div>
  </section>
</template>
<script>
import { ref } from 'vue'

const positiveMessages = [
  'he believes in you.',
  "he thinks you're awesome.",
  'he thinks you belong here.',
  'he knows you belong here.',
  "he thinks you've got this.",
  'he knows you can.',
]
const images = [5, 6, 7, 8, 10]

export default {
  setup() {
    let michaelImage = ref('')
    let positiveMessage = ref('')

    function recycle() {
      positiveMessage.value =
        positiveMessages[Math.floor(Math.random() * positiveMessages.length)]
      const mastNumber = Math.floor(Math.random() * images.length)
      michaelImage.value = `https://res.cloudinary.com/dk3rdh3yo/image/upload/g_auto,f_auto/v1607302424/ograph_${images[mastNumber]}.png`
    }

    recycle()

    return { michaelImage, positiveMessage, recycle }
  }
}
</script>
<style lang="scss" scoped>
section {
  .about {
    @apply flex justify-evenly items-center;
    @apply mx-auto;
    @apply p-8 pb-0;
    @apply w-full;
    @apply lg:max-w-4xl xl:max-w-6xl;
    @apply text-base;

    @apply text-darkPurple dark:text-white;

    img {
      @apply hidden md:block;
      @apply -mt-32;
      height: min-content;
      width: 24em;
      @apply cursor-pointer;
    }

    div {
      @apply w-full md:w-1/2;
      @apply pb-8 md:pb-0 md:pl-6;

      h2 {
        @apply flex items-center;
        @apply font-cairo font-bold uppercase;
        @apply text-3xl md:text-4xl;
        span {
          @apply flex;
          @apply ml-1;
          @apply py-0 px-2;
          @apply text-white dark:text-darkPurple;
          @apply bg-blue-500 dark:bg-bbbblue;
        }
      }
      p {
        @apply py-3;

        a {
          @apply text-blue-500 dark:text-bbbpink;
          @apply border-b-2 border-transparent;
          &:hover {
            border-image-slice: 1;
            border-image-source: linear-gradient(to right, #ff00ff, #00ffff);
          }
        }

        span {
          @apply ml-1;
          @apply pt-0 pb-1 px-2;
          @apply font-bold;
          @apply text-white;
          @apply bg-blue-500 dark:bg-bbbpink;
        }
      }
    }
  }
}
</style>
